# Generated by Django 5.1.6 on 2025-02-19 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='country',
            new_name='campus',
        ),
        migrations.AddField(
            model_name='player',
            name='sport_type',
            field=models.CharField(blank=True, choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('tennis', 'Tennis'), ('chess', 'Chess'), ('fps', 'FPS Game'), ('moba', 'MOBA Game'), ('battle_royale', 'Battle Royale'), ('ctf', 'Capture The Flag'), ('cp', 'Competitive Programming'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team'),
        ),
    ]
