# Generated by Django 5.1.6 on 2025-02-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_rename_country_player_campus_player_sport_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='nickname',
            new_name='login',
        ),
    ]
