# Generated by Django 5.1.6 on 2025-02-18 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('esports', 'eSports'), ('ctf', 'CTF Contest'), ('cp', 'Competitive Programming'), ('other', 'Other')], default='sports', max_length=10)),
                ('sport_type', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('tennis', 'Tennis'), ('chess', 'Chess'), ('fps', 'FPS Game'), ('moba', 'MOBA Game'), ('battle_royale', 'Battle Royale'), ('ctf', 'Capture The Flag'), ('cp', 'Competitive Programming'), ('other', 'Other')], default='other', max_length=20)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('player', 'Player'), ('captain', 'Captain'), ('coach', 'Coach'), ('analyst', 'Analyst'), ('support', 'Support'), ('substitute', 'Substitute'), ('other', 'Other')], default='player', max_length=15)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='player.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='team.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'team'), name='unique_player_per_sport')],
            },
        ),
    ]
