# Generated by Django 5.1.6 on 2025-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sport_type',
            field=models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('tennis', 'Tennis'), ('chess', 'Chess'), ('fps', 'FPS Game'), ('moba', 'MOBA Game'), ('battle_royale', 'Battle Royale'), ('ctf', 'Capture The Flag'), ('cp', 'Competitive Programming'), ('other', 'Other')], default='football', max_length=20),
        ),
    ]
